### ISSUE TITLE
Issue with space-step

### ISSUE THREAD

**Issue by paines** [ChrisBlom/chicken-chipmunk-7#1]
Hi, sorry for bothering. I compiled your Chipmunk egg and have this little snippet which fails at the space-step function. Any idea what I am doing wrong ?

```
(use chipmunk)


(define *time* (/ 1 60))
(define space (space-new))
(space-set-gravity space (v 0 -9.81))
(define player-one (body-alloc))
(set! (body-position player-one) (v 10 10))
(space-add-body space player-one)
(define circle-shape (circle-shape-new player-one 0.3 (v 0.0 0.0)))
(space-add-shapes space circle-shape)

(do ((i 0 (add1 i)))
    ((> i 100))
  (space-step space *time*)
  (print "player-one pos" (body-position player-one)))
```

**Comment by ChrisBlom** [comment]
You need to initialise the player-one body with a mass and inertia using `body-init` before calling `space-step`.

For example:
```scheme
 (body-init player-one 1.0 1.0)
```
Instead of `body-alloc` followed by `body-init` it is better to use `body-new`.
`body-alloc` is more of an internal thing

**Comment by ChrisBlom** [comment]
With `body-new`:

```scheme
(use chipmunk)

(define *time* (/ 1 60))
(define space (space-new))
(space-set-gravity space (v 0 -9.81))
(define player-one (body-new 1.0 1.0))
(set! (body-position player-one) (v 10 10))
(space-add-body space player-one)
(define circle-shape (circle-shape-new player-one 0.3 (v 0.0 0.0)))
(space-add-shapes space circle-shape)

(do ((i 0 (add1 i)))
    ((> i 100))
  (space-step space *time*)
  (print "player-one pos" (body-position player-one)))

```

**Comment by paines** [comment]
Thank you very much. Really appreciate it!

**Comment by paines** [comment]
Sorry, again. How did you find out what the problem is? Only from experience with the Chipmunk API or did some Chicken magic tell you that. From the error mesasge I was not able to figure it out...

**Comment by ChrisBlom** [comment]
Yeah, the error message is not very helpful, I knew from experience with the Chipmunk API.

**Comment by ChrisBlom** [comment]
[Here](http://chipmunk-physics.net/release/ChipmunkLatest-Docs/#Basics-Memory) is some info about alloc and new.

**Comment by paines** [comment]
I think I understand it better now. Thanks!
